[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Heng", email = "31088159+shiukaheng@users.noreply.github.com"},
]
dependencies = [
    "websockets>=11.0.3",
    "cryptography>=41.0.3",
]
requires-python = ">=3.11"
license = {text = "MIT"}
